# Generated by Django 5.2.9 on 2026-01-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Member', 'Member'), ('Viewer', 'Viewer')], default='Viewer', max_length=10),
        ),
    ]
