# Generated by Django 5.2.9 on 2026-01-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': {('view_objects', 'can view objects')}},
        ),
    ]
