# Generated by Django 5.2.9 on 2026-01-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': {('change_obj', 'Can Change Objects'), ('delete_obj', 'Can Delete Objects'), ('view_obj', 'Can View Objects')}},
        ),
    ]
