# Generated by Django 5.2.9 on 2026-01-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': {('change_task_obj', 'Can Change Task Objects'), ('delete_task_obj', 'Can Delete Task Objects'), ('view_task_obj', 'Can View Task Objects')}},
        ),
    ]
