# Generated by Django 5.2.9 on 2026-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'permissions': {('change_status_obj', 'Can change task objects'), ('delete_status_obj', 'Can delete task objects'), ('view_status_obj', 'Can view status objects')}},
        ),
    ]
