# Generated by Django 5.2.9 on 2026-01-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_taskstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'permissions': {('change_status_obj', 'Can change status objects'), ('delete_status_obj', 'Can delete status objects'), ('view_status_obj', 'Can view status objects')}},
        ),
    ]
